# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: purcell/setup-emacs@master
        with:
          version: 24.5

      # Runs a set of commands using the runners shell
      - name: Run a EMACS
        run: |
          cat index.sh | /bin/sh
          emacs --batch --eval "(progn (package-initialize) (package-refresh-contents) (package-install 'org))"
          emacs --batch --no-init-file --load publish.el --funcall org-publish-all
